### ISSUE TITLE
Where are the files located in drive?  Storing files in folders?  Sharing files?  Working offline?

### ISSUE THREAD

**Issue by joebywan** [stewartmcgown/uds#59]
I managed to upload my first file using the tool, but when I check the drive web interface, it doesn't show any files anywhere except the recent section.

Is there a way to view/organise the files in the drive into folders?  So each group of files making up a file can be in it's own folder, so it can be shared?

Does UDS have a function to work with a shared folder to download & convert a file from the google docs back to the original?

Alternatively if someone downloaded all of the base64 files, can UDS be put to work on the files to convert it back into the original file offline?

I know it's a bunch of different questions, just what's coming to mind.  You're definitely onto something here.

**Comment by SammyHass** [comment]
1. Files are located in ‘UDS Root’ - Search for that in Drive.
2. What you described is essentially what you’ll see if you go to ‘UDS Root’ whereby docs are in folders which are named using their titles. Of course, drive not particularly helpful for viewing though.
3. UDS can download files you’ve uploaded and put them back into their original form. There are no sharing functionalities in the program at this time.
4. UDS simply utilises a base64 en/decoding algorithm in order to reach its goal. Therefore, there are no features that can take downloaded base64 files and output the original data. This is with the exception of any files being downloaded using UDS as opposed to what I believe you’re saying (correct me if I’m wrong) which is to just download one of the folders from Drive which would just give you a bunch of Word Docs or PDF files anyway.

Hope that helps.
